### ISSUE TITLE
addr:street invalid name processing

### ISSUE THREAD

**Issue by james2432** [osmottawa/etl2osm#15]
CR 466 is changed to Hwy 466 processed. 
Which should resolve to either CR 466
Sample addresses that output this:
http://www.openstreetmap.org/relation/1240329#map=18/28.91564/-81.93959

**Comment by DenisCarriere** [comment]
Which dataset are you referencing and which fields?
Also we can't resolve poor data, this will only be the 95% solution.
At the moment, "CR" isn't getting processed to Hwy based from the Model:
https://github.com/osmottawa/etl2osm/blob/master/etl2osm/models.py

Now if the datasets are mixing up Street name for Suffixes and doing a bunch of crazy nonesense then that's their fault and we shouldn't do test cases on that.

**Comment by james2432** [comment]
CR roads have alias names which openstreetmaps have adopted for highways aparently. Screenshot of data in QGIS
![alias for cr](https://cloud.githubusercontent.com/assets/498547/10729072/44445e26-7bbd-11e5-9296-7b50d9f9b5c7.JPG)

**Comment by james2432** [comment]
HWY isnt getting processed because you need to do a substring of the basestreet to replace HWY with Highway. In Sumter data there are streets like this too and some start with C-XYZ but should be written CR XYZ (there are also CR UVW in sumter)

**Comment by james2432** [comment]
Openaddresses may have implemented it via "split"
https://github.com/openaddresses/openaddresses/blob/master/sources/ca/on/city_of_welland.json

**Comment by james2432** [comment]
If we are trying to follow openaddress schema:
https://github.com/openaddresses/openaddresses/blob/master/CONTRIBUTING.md#attribute-functions
the regexp would be used to deal with this.

**Comment by DenisCarriere** [comment]
Too bad their split function is Deprecated, it just seems like it's a hard battle to win when you're looking at global datasets, it's hard for everyone to conform the same way. It feels like they tried to fix this issue and then gave up.

**Comment by james2432** [comment]
I think thats why they created a regular expressions to replace problems that they couldnt fix other wise

**Comment by DenisCarriere** [comment]
Yea I like having Regular expressions built in

**Comment by DenisCarriere** [comment]
I've added a bunch of Regex built in functions, try to "break" it by adding more test functions in the `tests/test_transform.py`.

Here's the Regex tests:
```python
def test_transform_regex():
    conform = {'function': 'regexp', 'field': 'NAME', 'pattern': '^([0-9]+)'}
    properties = {'NAME': '65 Street Name'}
    assert etl2osm.clean_field(properties, conform) == '65'


def test_transform_regex_replace():
    conform = {'function': 'regexp', 'field': 'NAME', 'pattern': '^(HWY)', 'replace': 'Highway'}
    properties = {'NAME': 'HWY 174'}
    assert etl2osm.clean_field(properties, conform) == 'Highway 174'
```

I'll continue to work on this.

**Comment by DenisCarriere** [comment]
@james2432 Test out the Regex function, if there's still an issue let me know and we can reopen it again.
