### ISSUE TITLE
Transform.py List raises value error

### ISSUE THREAD

**Issue by james2432** [osmottawa/etl2osm#16]
When properties has a Null value it raises an invalid value error
See image of the value of properties and the value of field that raises a value error (Lake county)
![bug](https://cloud.githubusercontent.com/assets/498547/10850837/0fd72dd2-7efe-11e5-9741-3d45a4fa5b31.png)

**Comment by DenisCarriere** [comment]
It's still a bit buggy, I haven't tested everything together (Extract, Transform, Load).
I've been focusing on the Transform part, I'll be looking into this tomorrow.

**Comment by DenisCarriere** [comment]
@james2432 Should be fixed now, I'm going to be testing the Load (Saving file) now, once that's all tested it should be ready to go.
